name: Publish Docker image

on:
  pull_request:
    types: [closed]
    branches: [main]

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Get the bun version
        id: vars
        run: echo "::set-output name=bun_version::$(grep -oP '(?<=oven/bun:)[^ ]*' Dockerfile)"

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: 0tii/bun-chromium:${{ steps.vars.outputs.bun_version }}
